Matriculation Exam/Exam 09.05.2021/RentACar/Web/Controllers/CarController.cs
using RentACar.Services;
using Microsoft.AspNetCore.Mvc;
using RentACar.Web.Models.Car;
using AutoMapper;
using RentACar.Services.Models.Car;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using System.Linq;
using System.Collections.Generic;
using System;
using RentACar.Services.Models.CarRent;

namespace RentACar.Web.Controllers
{
	[Authorize]
	public class CarController : Controller
	{
		private readonly IMapper _autoMapper;
		private readonly CarService _carService;
		private readonly CarRentService _carRentService;

		public CarController(CarService carService, IMapper autoMapper, CarRentService carRentService)
		{
			this._carService = carService;
			this._autoMapper = autoMapper;
			this._carRentService = carRentService;
		}

		[HttpGet]
		public IActionResult Index(string onlyFree = null, DateTime startTime = default(DateTime), DateTime endTime = default(DateTime))
		{
			bool onlyFreeCars = true;
			List<CarServiceModel> serviceOut = null;
			if (onlyFree == "true")
				serviceOut = this._carService.GetFree();
			else if (startTime != default(DateTime) && endTime != default(DateTime))
				serviceOut = this._carService.GetBetweenDates(startTime, endTime);
			else if (startTime != default(DateTime))
				serviceOut = this._carService.GetFromStartDate(startTime);
			else if (endTime != default(DateTime))
				serviceOut = this._carService.GetFromEndDate(endTime);
			else
			{
				onlyFreeCars = false;
				serviceOut = this._carService.GetAll();
			}

			var model = serviceOut
				.Select(c => this._autoMapper.Map<CarViewModel>(c))
				.ToList();
			
			model.ForEach(c => c.IsFree = onlyFreeCars);

			return View(model);
		}

		[HttpGet]
		public async Task<IActionResult> Rent(string carId = null, double price = 0)
		{
			if (carId == null)
				return RedirectToAction("Index");

			CarServiceModel serviceOut = await this._carService.GetByIdAsync(Guid.Parse(carId));
			var model = this._autoMapper.Map<CarRentViewModel>(serviceOut);
			if (price > 0)
				model.TotalPrice = price;

			return View(model);
		}

		[HttpPost]
		public async Task<IActionResult> Rent(string carId = null, DateTime startTime = default(DateTime), DateTime endTime = default(DateTime), double totalPrice = 0)
		{
			if (carId == null || startTime == default(DateTime) || endTime == default(DateTime) || totalPrice <= 0)
				return RedirectToAction("Index");

			var serviceModel = new CreateCarRentServiceModel();
			serviceModel.StartDate = startTime;
			serviceModel.EndDate = endTime;
			serviceModel.CarId = Guid.Parse(carId);
			serviceModel.RentPrice = totalPrice;

			var result = await this._carRentService.Create(serviceModel, HttpContext.User);

			if (result)
				return RedirectToAction("Index");
			else
				return RedirectToAction("Rent", new { carId = carId, startTime = startTime.ToString("s"), endTime = endTime.ToString("s"), price = totalPrice });
		}

		[HttpPost]
		public async Task<IActionResult> GetPrice(string carId = null, DateTime startTime = default(DateTime), DateTime endTime = default(DateTime))
		{
			if (carId == null || startTime == default(DateTime) || endTime == default(DateTime))
				return RedirectToAction("Index");

			var total = await this._carService.CalculatePrice(Guid.Parse(carId), startTime, endTime);

			return RedirectToAction("Rent", new { carId = carId, startTime = startTime.ToString("s"), endTime = endTime.ToString("s"), price = total });
		}

	}
}

Matriculation Exam/Exam 09.05.2021/RentACar/Web/Views/Shared/_FooterContent.cshtml
<div class="border-top box-shadow">
	<div class="footer-content middle-content-container">
		<section>
			Rent A Car - 2021
		</section>
		<div class="flex-spacer"></div>
	</div>
</div>

Matriculation Exam/Exam 09.05.2021/RentACar/Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"]</title>
	<link rel="stylesheet" href="~/css/site.css" />
	<link rel="stylesheet" href="~/css/styles.css" />
</head>
<body>
	<header>
		<partial name="_Navbar.cshtml" />
	</header>

	<main class="main">
		<div class="middle-content-container">
			@RenderBody()
		</div>
	</main>

	<footer class="border-top box-shadow">
		<partial name="_FooterContent.cshtml" />
	</footer>
</body>
</html>

Matriculation Exam/Exam 09.05.2021/RentACar/Web/Views/Shared/_Navbar.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager

<nav class="navbar border-bottom box-shadow">
	<div class="middle-content-container navbar-contents">
		<section>
			<b>RentACar</b>
			<a asp-controller="Home" asp-action="Index">Home</a>
			<a asp-controller="Car" asp-action="Index">Cars</a>
		</section>
		<div class="flex-spacer"></div>
		<section>
			@if (SignInManager.IsSignedIn(User))
			{
				<a asp-controller="Account" asp-action="Profile" asp-route-username="@UserManager.GetUserName(User)">
					@UserManager.GetUserName(User)
				</a>

				<form asp-controller="Account" asp-action="Logout" method="post">
					<input type="submit" value="Logout">
				</form>
			}
			else
			{
				<a asp-controller="Account" asp-action="Login">Login</a>
				<a asp-controller="Account" asp-action="Register">Register</a>
			}
		</section>
	</div> 
</nav>