Matriculation Exam/Exam 16.05.2021/FilmWorld/Web/FilmWorld.Web/Controllers/CatalogController.cs
using System;
using System.Threading.Tasks;
using AutoMapper;
using FilmWorld.Services.Interfaces;
using FilmWorld.Services.Models.Catalog;
using FilmWorld.Web.Models.Catalog;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;

namespace FilmWorld.Web.Controllers
{
    [Authorize]
	public class CatalogController : Controller
	{
		private readonly IMapper _autoMapper;
		private readonly ICatalogService _service;
		private readonly IUserService _userService;
		private readonly IFilmService _filmService;

		public CatalogController(IMapper autoMapper, ICatalogService service, IUserService userService, IFilmService filmService)
		{
			this._autoMapper = autoMapper;
			this._service = service;
			this._userService = userService;
			this._filmService = filmService;
		}

		[HttpGet]
		public IActionResult Index()
		{
			string userId = HttpContext.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
			HashSet<CatalogServiceModel> serviceModels = this._service.GetUserCatalogs(Guid.Parse(userId));

			List<CatalogWebModel> webModel = serviceModels
				.Select(x => this._autoMapper.Map<CatalogWebModel>(x))
				.ToList();
			return View(webModel);
		}

		[HttpGet]
		public async Task<IActionResult> Details(string id)
		{
			CatalogServiceModel serviceModel = await this._service.GetByIdAsync(Guid.Parse(id));
			serviceModel.Films = await this._service.GetAllFilms(Guid.Parse(id));

			CatalogWebModel webModel = this._autoMapper.Map<CatalogWebModel>(serviceModel);
			return View(webModel);
		}


		[HttpGet]
		public IActionResult Create()
		{
			return View();
		}

		[HttpPost]
		public async Task<IActionResult> Create(CreateCatalogWebModel webModel)
		{
			if (!ModelState.IsValid)
				return View(webModel);

			CatalogServiceModel serviceModel = this._autoMapper.Map<CatalogServiceModel>(webModel);
			
			string userId = HttpContext.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;

			bool result = await this._service.CreateAsync(serviceModel, Guid.Parse(userId));

			if (result)
				return RedirectToAction("Index");
			else
				return RedirectToAction("Create");
		}

		[HttpGet]
		public async Task<IActionResult> Edit(string id)
		{
			CatalogServiceModel serviceModel = await this._service.GetByIdAsync(Guid.Parse(id));

			EditCatalogWebModel editCatalogWebModel = this._autoMapper.Map<EditCatalogWebModel>(serviceModel);
			return View(editCatalogWebModel);
		}

		[HttpPost]
		public async Task<IActionResult> Edit(EditCatalogWebModel webModel)
		{
			if (!ModelState.IsValid)
				return View(webModel);

			CatalogServiceModel serviceModel = this._autoMapper.Map<CatalogServiceModel>(webModel);

			bool result = await this._service.EditAsync(serviceModel);

			if (result)
				return RedirectToAction("Details", new { id = webModel.Id.ToString() });
			else
				return RedirectToAction("Edit", new { id = webModel.Id.ToString() });
		}

		[HttpGet]
		public IActionResult AddFilm(string id)
		{
			string userId = HttpContext.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;

			List<CatalogWebModel> webModel = this._service.GetUserCatalogs(Guid.Parse(userId))
				.Select(c => this._autoMapper.Map<CatalogWebModel>(c))
				.ToList();
			return View(webModel);
		}

		[HttpPost]
		public async Task<IActionResult> AddFilm(string filmId, string[] catalogIds)
		{
			bool result = await this._service.AddFilmToCatalogs(Guid.Parse(filmId), catalogIds.Select(c => Guid.Parse(c)).ToArray());

			if (result)
				return RedirectToAction("Index");
			else
				return RedirectToAction("AddFilm", new { id = filmId });
		}

		[HttpGet]
		public IActionResult Delete()
		{
			return View();
		}

		[HttpPost]
		public async Task<IActionResult> Delete(string id)
		{
			bool result = await this._service.DeleteAsync(Guid.Parse(id));

			if (result)
				return RedirectToAction("Index");
			else
				return RedirectToAction("Delete", new { id = id });
		}
	}
}

Matriculation Exam/Exam 16.05.2021/FilmWorld/Web/FilmWorld.Web/Controllers/FilmController.cs
using System;
using System.Threading.Tasks;
using AutoMapper;
using FilmWorld.Services.Interfaces;
using FilmWorld.Services.Models.Film;
using FilmWorld.Web.Models.Film;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using FilmWorld.Common;

namespace FilmWorld.Web.Controllers
{
	[Authorize]
	public class FilmController : Controller
	{
		private readonly IMapper _autoMapper;
		private readonly IFilmService _service;

		public FilmController(IMapper autoMapper, IFilmService service)
		{
			this._autoMapper = autoMapper;
			this._service = service;
		}

		[HttpGet]
		public async Task<IActionResult> Index(string query)
		{
			List<FilmServiceModel> serviceModels = (query == null)
				? await this._service.GetAllAsync()
				: await this._service.GetAllByQueryAsync(query);

			List<FilmWebModel> webModel = serviceModels
				.Select(x => this._autoMapper.Map<FilmWebModel>(x))
				.ToList();
			return View(webModel);
		}

		[HttpGet]
		public async Task<IActionResult> Details(string id)
		{
			FilmServiceModel serviceModel = await this._service.GetByIdAsync(Guid.Parse(id));

			FilmWebModel webModel = this._autoMapper.Map<FilmWebModel>(serviceModel);
			return View(webModel);
		}


		[HttpGet]
		[Authorize(Roles = RoleConst.Admin)]
		public IActionResult Create()
		{
			return View();
		}

		[HttpPost]
		[Authorize(Roles = RoleConst.Admin)]
		public async Task<IActionResult> Create(CreateFilmWebModel webModel)
		{
			if (!ModelState.IsValid)
				return View(webModel);

			FilmServiceModel serviceModel = this._autoMapper.Map<FilmServiceModel>(webModel);

			bool result = await this._service.CreateAsync(serviceModel);

			if (result)
				return RedirectToAction("Index");
			else
				return RedirectToAction("Create");
		}

		[HttpGet]
		[Authorize(Roles = RoleConst.Admin)]
		public async Task<IActionResult> Edit(string id)
		{
			FilmServiceModel serviceModel = await this._service.GetByIdAsync(Guid.Parse(id));

			EditFilmWebModel editFilmWebModel = this._autoMapper.Map<EditFilmWebModel>(serviceModel);
			return View(editFilmWebModel);
		}

		[HttpPost]
		[Authorize(Roles = RoleConst.Admin)]
		public async Task<IActionResult> Edit(EditFilmWebModel webModel)
		{
			if (!ModelState.IsValid)
				return View(webModel);

			FilmServiceModel serviceModel = this._autoMapper.Map<FilmServiceModel>(webModel);

			bool result = await this._service.EditAsync(serviceModel);

			if (result)
				return RedirectToAction("Details", new { id = webModel.Id.ToString() });
			else
				return RedirectToAction("Edit", new { id = webModel.Id.ToString() });
		}

		[HttpGet]
		[Authorize(Roles = RoleConst.Admin)]
		public IActionResult Delete()
		{
			return View();
		}

		[HttpPost]
		public async Task<IActionResult> Delete(string id)
		{
			bool result = await this._service.DeleteAsync(Guid.Parse(id));

			if (result)
				return RedirectToAction("Index");
			else
				return RedirectToAction("Delete", new { id = id });
		}
	}
}

Matriculation Exam/Exam 16.05.2021/FilmWorld/Web/FilmWorld.Web/Views/Film/Create.cshtml
@model CreateFilmWebModel
@{
	ViewData["Title"] = "Creating a new Film";
}

<form asp-controller="Film" asp-action="Create" method="post" enctype="multipart/form-data">
	<input type="text" asp-for="Name" placeholder="Name">
	<span asp-validation-for="Name" class="form-error"></span>

	<input type="file" asp-for="Photo">
	<span asp-validation-for="Photo" class="form-error"></span>

	<input type="text" asp-for="Description" placeholder="Description">
	<span asp-validation-for="Description" class="form-error"></span>

	<input type="date" asp-for="PremiereDate" placeholder="PremiereDate">
	<span asp-validation-for="PremiereDate" class="form-error"></span>

	<input type="submit" value="Create">
</form>

@if (Model != null)
{
	<p class="form-error">
		Couldn't create Film!
	</p>
}

Matriculation Exam/Exam 16.05.2021/FilmWorld/Web/FilmWorld.Web/Views/Film/Delete.cshtml
@{
	ViewData["Title"] = "Deleting Film";
}

<p>
	Are you sure you want to delete this Film?
</p>
<form asp-controller="Film" asp-action="Delete" method="post">
	<!-- Gets the id from the URL and sets it to the model -->
	<input type="hidden" name="id" value="@Context.Request.Query["id"]">
	
	<input type="submit" value="Delete">
</form>

Matriculation Exam/Exam 16.05.2021/FilmWorld/Web/FilmWorld.Web/Views/Film/Details.cshtml
@model FilmWebModel
@{
	ViewData["Title"] = "Film";
}

<section class="card">
	<div>
		<b>
			@Model.Name
		</b>
		<p>
			@Model.Description
			<br>
			Premiered: @Model.PremiereDate
		</p>
		<div class="buttons">
			<form asp-controller="Catalog" asp-action="AddFilm" method="get">
				<input type="hidden" name="Id" value="@Model.Id">

				<input type="submit" value="Add to a catalog">
			</form>
			@if (User.IsInRole("Administrator"))
			{
				<form asp-controller="Film" asp-action="Edit" method="get">
					<input type="hidden" name="Id" value="@Model.Id">
					<input type="submit" value="Edit">
				</form>

				<form asp-controller="Film" asp-action="Delete" method="get">
					<input type="hidden" name="Id" value="@Model.Id">
					<input type="submit" value="Delete">
				</form>
			}
		</div>
	</div>
	<img src="@Model.PhotoURL">
</section>

Matriculation Exam/Exam 16.05.2021/FilmWorld/Web/FilmWorld.Web/Views/Film/Edit.cshtml
@model EditFilmWebModel
@{
	ViewData["Title"] = "Editing Film";
}

<form asp-controller="Film" asp-action="Edit" method="post" enctype="multipart/form-data">
	<!-- Gets the id from the URL and sets it to the model -->
	<input type="hidden" asp-for="Id" value="@Context.Request.Query["id"]">
	<label asp-for="Name">Name</label>
	<input type="text" asp-for="Name" placeholder="Name">
	<span asp-validation-for="Name" class="form-error"></span>

	<label asp-for="Photo">Photo</label>
	<input type="file" asp-for="Photo">
	<span asp-validation-for="Photo" class="form-error"></span>

	<label asp-for="Description">Description</label>
	<input type="text" asp-for="Description" placeholder="Description">
	<span asp-validation-for="Description" class="form-error"></span>

	<label asp-for="PremiereDate">PremiereDate</label>
	<input type="date" asp-for="PremiereDate" placeholder="PremiereDate">
	<span asp-validation-for="PremiereDate" class="form-error"></span>

	<input type="submit" value="Edit">
</form>

Matriculation Exam/Exam 16.05.2021/FilmWorld/Web/FilmWorld.Web/Views/Film/Index.cshtml
@model IEnumerable<FilmWebModel>
@{
	ViewData["Title"] = "Films";
}

@if (User.IsInRole("Administrator"))
{
	<a asp-controller="Film" asp-action="Create">Create</a>
}
<form asp-controller="Film" asp-action="Index" method="get" class="search-form">
	<input type="text" name="query" placeholder="Search" value="@Context.Request.Query["query"]">
	<input type="submit" value="Search">
</form>
<div>
	@foreach (var item in Model)
	{
		<section class="card">
			<div>
				<b>
					@item.Name
				</b>
				<p>
					@item.Description
					<br>
					Premiered: @item.PremiereDate
				</p>
				<div class="buttons">
					<form asp-controller="Film" asp-action="Details" method="get">
						<input type="hidden" name="Id" value="@item.Id">

						<input type="submit" value="Details">
					</form>
					@if (User.IsInRole("Administrator"))
					{
						<form asp-controller="Film" asp-action="Edit" method="get">
							<input type="hidden" name="Id" value="@item.Id">
							<input type="submit" value="Edit">
						</form>

						<form asp-controller="Film" asp-action="Delete" method="get">
							<input type="hidden" name="Id" value="@item.Id">

							<input type="submit" value="Delete">
						</form>
					}
				</div>
			</div>
			<img src="@item.PhotoURL">
		</section>
	}
</div>

@if (Model.Count() == 0)
{
	<div class="form-error">
		We couldn't find any films!
	</div>
}